# Generated by Django 4.2.30 on 2026-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0004_catalognode_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogedge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='catalognode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='catalognode',
            name='label',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='catalognode',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedgraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
