# Generated by Django 4.2.30 on 2026-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0005_catalogedge_created_at_catalognode_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdiNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('label', models.CharField(db_index=True, max_length=500)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('sheet', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='OdiEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=500)),
                ('target_id', models.CharField(db_index=True, max_length=500)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'unique_together': {('source_id', 'target_id', 'action')},
            },
        ),
    ]
